name: CI - Build and Test

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar Yarn
        run: npm install -g yarn

      - name: Remover arquivos de lock do NPM
        run: rm -f package-lock.json

      - name: Instalar dependências
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Buildar projeto
        run: yarn build

      - name: Rodar testes unitários
        run: yarn test:unit
